version: "3.4"



services:
  mongo:
    image: mongo
    container_name: store-mongo
    env_file:
      - .env
    ports:
      - ${S_MONGODB_PORT}:${S_MONGODB_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${S_MONGODB_DB}
    networks:
      - servicenet

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: store-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - servicenet

  users:
    image: store-users
    ports:
      - ${S_USERS_PORT}:${S_USERS_PORT}
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
    networks:
      - servicenet
    environment:
      - S_AMQP_ADDRESS=${S_AMQP_ADDRESS}
      - S_AMQP_QUEUE_NAME=${S_AMQP_QUEUE_NAME}
      - S_AMQP_EXCHANGE_NAME=${S_AMQP_EXCHANGE_NAME}
      - S_MONGODB_DB=${S_MONGODB_DB}
      - S_MONGODB_HOST=${S_MONGODB_HOST}
      - S_MONGODB_PORT=${S_MONGODB_PORT}
      - S_USERS_PORT=${S_USERS_PORT}

  products:
    image: store-products
    ports:
      - ${S_PRODUCTS_PORT}:${S_PRODUCTS_PORT}
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
    networks:
      - servicenet
    environment:
      - S_MONGODB_DB=${S_MONGODB_DB}
      - S_MONGODB_HOST=${S_MONGODB_HOST}
      - S_MONGODB_PORT=${S_MONGODB_PORT}
      - S_PRODUCTS_PORT=${S_PRODUCTS_PORT}

  emailer:
    image: store-emailer
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - S_AMQP_ADDRESS=${S_AMQP_ADDRESS}
      - S_AMQP_QUEUE_NAME=${S_AMQP_QUEUE_NAME}
      - S_AMQP_EXCHANGE_NAME=${S_AMQP_EXCHANGE_NAME}
      - S_SMTP_FROM=${S_SMTP_FROM}
      - S_SMTP_PASSWORD=${S_SMTP_PASSWORD}
      - S_SMTP_HOST=${S_SMTP_HOST}
      - S_SMTP_PORT=${S_SMTP_PORT}
    networks:
      - servicenet

  grafana:
    image: grafana/grafana:7.3.7
    container_name: store-grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: store-prometheus
    volumes:
      - ../metrics:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    env_file:
      - .env
    ports:
      - 9090:9090
    restart: on-failure
    networks:
      - monitoring
      - servicenet

networks:
  servicenet:
    driver: bridge
  monitoring:
