global:
  scrape_interval: 15s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: products
    static_configs:
      - targets: ["products:9100"]

  - job_name: users
    static_configs:
      - targets: ["users:9100"]