global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'store-products'
    static_configs:
      - targets: ["products:8181"]

  - job_name: 'store-users'
    static_configs:
      - targets: ["users:8282"]