global:
  scrape_interval: 15s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: productservice
    static_configs:
      - targets: ["productservice:9100"]

  - job_name: userservice
    static_configs:
      - targets: ["userservice:9100"]